### ISSUE TITLE
Failed on Azure Resources Deployment - Microsoft.Web/Sites/control

### ISSUE THREAD

**Issue by berryst** [OfficeDev/microsoft-teams-apps-workplaceawards#10]
Hi,
I got the following error on deploying the Azure components 

![image](https://user-images.githubusercontent.com/8452145/92184032-1ace5b00-eea4-11ea-953d-e85cc8b3a413.png)
![image](https://user-images.githubusercontent.com/8452145/92184047-23bf2c80-eea4-11ea-8aba-6d90a520c31a.png)

![image](https://user-images.githubusercontent.com/8452145/92184053-29b50d80-eea4-11ea-8262-92c59ee1e490.png)

**Comment by mgdarg** [comment]
Any news about this issue? we have the same problem. We need your help.

Thanks a lot!! Regards

**Comment by v-smahaj** [comment]
Can you please try selecting higher App Service plan like S2 or S3 and try again.
Once deployment is completed, you can go back to smaller App Service plan.
Let us know if issue still persists.
