### ISSUE TITLE
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by edserran** [OfficeDev/microsoft-teams-apps-workplaceawards#12]
I did follow the deployment guide and properly uploaded the app to Teams, but it's not working.
_The resource you are looking for has been removed, had its name changed, or is temporarily unavailable._

**URL:** https://edgaragewplaceawards.azurefd.net/config-tab

**From deployment guide:**
_Replace <appbaseurl> placeholder in configurationTabs.configurableUrl with the Azure front door URL created i.e.'https://[BaseResourceName].azurefd.net'. For example if you chose contoso-workplaceawards then the appbaseurl will be https://contoso-workplaceawards.azurefd.net.
_Note: please make sure to keep the URL path /config-tab as is._

**Comment by v-smahaj** [comment]
Can you try to sync the code again to App Service.
Search for App Service in Azure portal => Click on Deployment Center in left nav and then click on Sync.
Let us know if issue still persists.
