### ISSUE TITLE
Unable to reach the app

### ISSUE THREAD

**Issue by Rrivero11** [OfficeDev/microsoft-teams-apps-workplaceawards#15]
After following all the steps in the deployment guide I face this issue.
https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d4-dbdb9fbe9d4fde56cf57da3cfe296a23/views/imgpsh_mobile_save

**Comment by v-smahaj** [comment]
Please validate your app service configuration. If resources are created in different tenant and Teams is in different one, tenant Id of tenant in which Teams reside should be added in configuration.
Please share more details about the issue, if it still persists.
