### ISSUE TITLE
Blank tab and "We're not currently in an active award cycle..." after install

### ISSUE THREAD

**Issue by kahopkin** [OfficeDev/microsoft-teams-apps-workplaceawards#16]
Did anyone have any success deploying the Workplace Awards  template?  I followed the guide to the last letter, have no errors, but I get a blank screen for the tab (after agreeing in the permission popup)

![image](https://user-images.githubusercontent.com/62229442/98045014-d86ac100-1df5-11eb-8c6d-48a222d4eecf.png)

 

, and for the bot, I get: 

![image](https://user-images.githubusercontent.com/62229442/98045085-ea4c6400-1df5-11eb-9e92-627793cd129b.png)

 

After installing it to a team, there is supposed to be a prompt to select R&R captain, and then supposed to be able to set up the award cycles. 
If anyone has an idea why it is all blank and why it is not working, I would appreciate it.  I am using Azure Front Door for the 'customDomainOption'.

**Comment by angon-coder** [comment]
Hello, same problem here. Did you manage to solve this issue?

Thanks!

**Comment by khopkins73** [comment]
yes, I got it working.  I ended up deleting all resources, deployments and re-deploying it with setting the Resource group location West US (it was East US), and used a literal tenant ID (because my subscription type does not allow to switch tenants).

**Comment by johnortiz29** [comment]
I followed the steps for deployment process but it is blank after uploading the app in Teams

**Comment by johnortiz29** [comment]
Can you help me build this workplace reward to my test tenant?

**Comment by johnortiz29** [comment]
@khopkins73 Can you help me build this workplace reward to my test tenant?

**Comment by v-smahaj** [comment]
We were not able to repro this issue at our end. 
Can you share exceptions logged in Application Insights.

**Comment by angon-coder** [comment]
Hello, I'm having this problem again. I see a white screen in the app tab. In Application Insights I get the following errors:

Message: Object reference not set to an instance of an object.
Exception type: System.NullReferenceException
Failed method: Microsoft.Teams.Apps.RewardAndRecognition.Helpers.TeamsInfoHelper+<GetTeamMemberAsync>d__6.MoveNext

FormattedMessage: Error occurred while fetching team member for team: ***@thread.tacv2 - user object id: ***
CategoryName: Microsoft.Teams.Apps.RewardAndRecognition.Helpers.TeamsInfoHelper
RequestPath: /api/ConfigureAdmin/teammembers
ActionName: Microsoft.Teams.Apps.RewardAndRecognition.Controllers.ConfigureAdminController.GetTeamMembersAsync (Microsoft.Teams.Apps.RewardAndRecognition)

System.NullReferenceException:
   at Microsoft.Teams.Apps.RewardAndRecognition.Helpers.TeamsInfoHelper+<GetTeamMemberAsync>d__6.MoveNext (Microsoft.Teams.Apps.RewardAndRecognition, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\home\site\repository\Source\Microsoft.Teams.Apps.RewardAndRecognition\Helpers\TeamsInfoHelper.cs:105)
