### ISSUE TITLE
[Feature Request] Anonymous Nominations

### ISSUE THREAD

**Issue by LinealMartyn** [OfficeDev/microsoft-teams-apps-workplaceawards#19]
Hi, Great project but have used it for a while, in some cases it would be preferable to allow anonymous nominations for a particular award.

Thanks

**Comment by v-smahaj** [comment]
For Workplace Awards repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
