### ISSUE TITLE
403 error - Forbidden

### ISSUE THREAD

**Issue by Peld460** [OfficeDev/microsoft-teams-apps-workplaceawards#20]
Hi folks!!!!

I'm trying to deploy this template, everything looks well but, in the Workplace Awards tab is not displaying. I got this error in the http call. 

![image](https://user-images.githubusercontent.com/79266727/108372417-cd814400-71cc-11eb-8358-7b213c9d5aae.png)

anyone know how fix this one?

**Comment by v-smahaj** [comment]
Can you verify configuration values in App Service. Validate if correct tenant Id is added in configuration.
Let us know if issue still persists.
