### ISSUE TITLE
Task modules don't show up in iOS devices

### ISSUE THREAD

**Issue by guptamayank516** [OfficeDev/microsoft-teams-apps-workplaceawards#25]
Workplace Awards app template's task modules is not showing up in iOS device. Just displaying blank screen. Attached Video for the same.

When trying to open the task module from iOS, getting 401 Unauthorised access every time and task module opens a blank page as shown in the attached video.

https://user-images.githubusercontent.com/83691614/117104928-a2090100-ad9a-11eb-9922-96cf6a373aca.mov

**Comment by v-smahaj** [comment]
SSO Authentication is not supported on iOS devices with Azure Front Door. Please use custom domains or remove Azure Front Door and it should work.
Let us know if issue still persists.
