### ISSUE TITLE
Reason For Nomination is limited to 300 characters instead of 300 words

### ISSUE THREAD

**Issue by dennispalmenco-myob** [OfficeDev/microsoft-teams-apps-workplaceawards#26]
Reason For Nomination is limited to 300 characters instead of 300 words

**Comment by v-smahaj** [comment]
For Workplace Awards repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement.
Thanks!

**Comment by dennispalmenco-myob** [comment]
@v-smahaj 

Thanks, we just deployed the app to our company with 3000+ employees with dynamic settings to add new employees and received a couple of issues.


The app response was 20+ seconds when loading the nomination card. The bot is double posting the in the channel.

https://user-images.githubusercontent.com/64561988/120555876-d16d6500-c44f-11eb-8b0e-5c7bf5ed20ce.mov


Endorsement issue: Unable to reach app 20+ seconds response
https://user-images.githubusercontent.com/64561988/120554669-214b2c80-c44e-11eb-8853-e167bcf0b6d3.mov


Random issue with the app: "Something went wrong try again in a few minutes"
<img width="1038" alt="Screen Shot 2021-06-03 at 9 24 51 AM" src="https://user-images.githubusercontent.com/64561988/120554243-9b2ee600-c44d-11eb-9255-ea99d0f1cc4e.png">

**Comment by dennispalmenco-myob** [comment]
@v-smahaj I opened another issue ticket for this
