### ISSUE TITLE
SingIn

### ISSUE THREAD

**Issue by dimaref** [OfficeDev/microsoft-teams-apps-workplaceawards#31]
I added the app to the channel, clicked sign in, opened my organization ADFS window and after successfully logging in the authorization pop-up window its closed and sign in buttin available again. it repeats. In the logs of the Azure application, successful Sing ins.available

**Comment by v-smahaj** [comment]
Hi @dimaref,
We were not able to repro this issue at our end. Can you verify configuration values and make sure tenant Id of tenant where app is installed is added in App Service configuration.
Can you help us with Application Insights logs and manifest (if possible), if issue still persists.
